version: "3"

services:
  back:
    image: node:16.14
    container_name: phishing_back
    build: ./ 
    tty: true
    stdin_open: true
    command: npm run dev
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - mongodb
    ports:
      - 3001:3001
    environment:
      - MONGO_URI=mongodb://mongodb:27017/phishing
  mongodb:
    image: mongo:5.0.7
    container_name: phishing_db
    volumes:
      - ./:/app
    restart: always
    ports:
      - 27017:27017

networks:
  default:
    name: phishing
